_sweep_: sweeps.legal_eval.LegalEval
_component_: recipes.legal_eval.LegalEval
name: LegalEval
llm:
  _component_: aligner.trainer.Trainer
  model: /common/home/users/d/dtnguyen.2019/scratchDirectory/Meta-Llama-3.1-8B-Instruct
  tokenizer: /common/home/users/d/dtnguyen.2019/scratchDirectory/Meta-Llama-3.1-8B-Instruct
  output_dir: /common/home/users/d/dtnguyen.2019/scratchDirectory/checkpoint/
  dataset:
    _component_: data.sg_regulation.SgRegulation
    split: train
    max_len: 1
    question_prompt: |
      I am going to describe a scenario.
      Does the scenario involve a violation of law?
      Tell me 'Yes' or 'No' and give me a short reason.
      Here is the scenario: {scenario}

      Provide your response by filling out the following forms (no markdown).
      Answer: string
      Reason: string
    answer_prompt: |
      Answer: {answer}
      Reason: {reason}
# llm:
  # _component_: aligner.editor.Editor
  # hparam: hparams/rome.yaml
  # dataset:
    # _component_: data.sg_regulation.SgRegulation
    # split: train
    # max_len: 1
    # question_prompt: |
      # I am going to describe a scenario.
      # Does the scenario involve a violation of law?
      # Tell me 'Yes' or 'No' and give me a short reason.
      # Here is the scenario: {scenario}

      # Provide your response by filling out the following forms (no markdown).
      # Answer: string
      # Reason: string
    # answer_prompt: |
      # Answer: {answer}
      # Reason: {reason}
# llm:
  # _component_: aligner.llama.Llama
  # model: /common/home/users/d/dtnguyen.2019/scratchDirectory/Meta-Llama-3.1-8B-Instruct
  # tokenizer: /common/home/users/d/dtnguyen.2019/scratchDirectory/Meta-Llama-3.1-8B-Instruct
dataset:
  _component_: data.sg_regulation.SgRegulation
  split: test
  max_len: 1
  question_prompt: |
    I am going to describe a scenario.
    Does the scenario involve a violation of law?
    Tell me 'Yes' or 'No' and give me a short reason.
    Here is the scenario: {scenario}

    Provide your response by filling out the following forms (no markdown).
    Answer: string
    Reason: string
  answer_prompt: |
    Answer: {answer}
    Reason: {reason}
